language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
env:
- DB=mysql
before_script: composer require atoum/atoum
script: vendor/bin/atoum
deploy:
  provider: gae
  keyfile: 
  project: testing-199406
before_install:
- openssl aes-256-cbc -K $encrypted_943c18221300_key -iv $encrypted_943c18221300_iv
  -in testing-jd-959e9a2500ab.json.enc -out testing-jd-959e9a2500ab.json -d
