language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
env:
- DB=mysql
before_script: composer require atoum/atoum
script: vendor/bin/atoum

before_install:
- openssl aes-256-cbc -K $encrypted_943c18221300_key -iv $encrypted_943c18221300_iv
  -in testing-jd-6c36f3a4bd4a.json.enc -out testing-jd-6c36f3a4bd4a.json -d

deploy:
  on: master
  provider: gae
  keyfile: testing-jd-6c36f3a4bd4a.json
  project: testing-199406
